FROM --platform=$BUILDPLATFORM golang:1.23-alpine AS builder
WORKDIR /src/backend
ARG TARGETOS
ARG TARGETARCH

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend ./
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /out/backend ./cmd/api

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/backend ./backend
EXPOSE 8080
CMD ["./backend"]
